### ISSUE TITLE
Cannot rejoin flute room

### ISSUE THREAD

**Issue by sysrqb** [asn-the-goblin-slayer/flute#3]
23:52:54 weechat     | python: stdout/stderr: Traceback (most recent call last):
  23:52:54 weechat     | python: stdout/stderr:   File "/home/violauser/.weechat/python/weechat_viola.py", line 74, in viola_command_cb
  23:52:54 weechat     | python: stdout/stderr:     commands.join_room_cmd(parsed_args, buf)
  23:52:54 weechat     | python: stdout/stderr:   File "viola/commands.py", line 25, in join_room_cmd
  23:52:54 weechat     | python: stdout/stderr:     viola.send_room_join(channel, server, buf)
  23:52:54 weechat     | python: stdout/stderr:   File "viola/viola.py", line 425, in send_room_join
  23:52:54 weechat     | python: stdout/stderr:     viola_room = account.register_viola_room(channel, server, buf)
  23:52:54 weechat     | python: stdout/stderr:   File "viola/accounts.py", line 81, in register_viola_room
  23:52:54 weechat     | python: stdout/stderr:     raise ViolaCommandError
  23:52:54 weechat     | python: stdout/stderr: NameError: global name 'ViolaCommandError' is not defined
  23:52:54 weechat =!= | python: error in function "viola_command_cb"`

**Comment by asn-d6** [comment]
A patch needs to be written here, so that if a user does `join-room` in an already initialized viola room, we forget about the old room and send a new `ROOM_JOIN` packet. Shouldn't be too much work.

Until them, please restart viola before you rejoin an already joined room :) :-1:
